name: example-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - dask
  - jupyterlab >=3.3.0,<4.0.0a0
  - jupyter_server <2.0.0
  - jupyterhub-singleuser >=3.1.0
